#!/bin/bash
export IFS=$'\n'

CMDNAME=`basename $0`

##
if [ $# -ne 1 ] ; then
	echo "Usage : ${CMDNAME} [directory | archive file]"
	exit 1
fi

for file in `find ${1} -iname "*.zip" -o -iname "*.rar" -o -iname "*.gz" -o -iname "*.7z" -o -iname "*.tar" -o -iname "*.tgz" -o -iname "*.bz2" -o -iname "*.xz"` ; do
	ext=${file##*.}
	ext_lc=${ext,,}

	case "$ext_lc" in
		"zip" ) unzip ${file} ;;
		"rar" ) unrar x ${file} ;;
		"gz" ) gzip -d ${file} ;;
		"7z" ) 7z x ${file} ;;
		"tar" ) tar -xvf ${file} ;;
                "tgz" ) tar -xvf ${file} ;;
                "bz2" ) tar -xvf ${file} ;;
                "xz" ) tar -xvf ${file} ;;
	esac

done

exit 0
