#!/bin/bash
export IFS=$'\n'

CMDNAME=`basename $0`

##
if [ $# -ne 1 ] ; then
	echo "Usage : ${CMDNAME} [directory | archive file]"
	exit 1
fi

for file in `find ${1} -iname "*.rar" -o -iname "*.zip" -o -iname "*.7z"` ; do
	ext=${file##*.}
	ext_lc=${ext,,}

	if [ $ext_lc = "rar" ] ; then
		unrar x ${file}
	fi

	if [ $ext_lc = "zip" ] ; then
		unzip ${file}
	fi

	if [ $ext_lc = "7z" ] ; then
	        7z x ${file}
	fi 
done

exit 0
